
trigger: none
stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: windows-latest
        variables: 
          REACT_APP_SEND_MESSAGE_SERVICE_ID: 'service_syy18xq'
          REACT_APP_SEND_MESSAGE_TEMPLATE_ID: 'template_c8p5sce'
          REACT_APP_SEND_MESSAGE_PUBLIC_KEY: 'uDytv20x8CsKfGK0k'
        steps:
          - task: Npm@1
            displayName: 'npm install'
            inputs:
              verbose: false

          - task: Npm@1
            displayName: 'npm run build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: build
              ArtifactName: drop

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzurePortalServiceConncetion'
              appType: 'webApp'
              WebAppName: 'davidcsizy'
              packageForLinux: '$(System.DefaultWorkingDirectory)/build'
          