
trigger: none
stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: windows-latest
        variables: 
          REACT_APP_SEND_MESSAGE_SERVICE_ID: 'testvalue'
        steps:
          - task: Npm@1
            displayName: 'npm install'
            inputs:
              verbose: false

          - task: Npm@1
            displayName: 'npm run build'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: build
              ArtifactName: drop

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzurePortalServiceConncetion'
              appType: 'webApp'
              WebAppName: 'davidcsizy'
              packageForLinux: '$(System.DefaultWorkingDirectory)/build'
          