stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: windows-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js dependencies'
          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: 'resume_site'
              publishLocation: 'pipeline'
