trigger: none
stages:
  - stage: CI
    displayName: Build solution and publish artifact
    jobs:
      - job: CI
        pool:
          vmImage: windows-latest
        steps:
          - task: AzureKeyVault@2
            inputs:
              connectedServiceName: 'AzurePortalServiceConncetion'
              keyVaultName: 'kv-resume-app'
              secretsFilter: '*'
              runAsPreJob: true
          - task: Bash@3
            displayName: Environment Variables
            env:
              REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
              REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
              REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKeyId)
            inputs:
              targetType: 'inline'
              script: 'env | sort'
          - task: Npm@1
            displayName: 'npm install'
            inputs:
              verbose: false

          - task: Npm@1
            displayName: 'npm run build'
            env:
              REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
              REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
              REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKeyId)
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'

          - task: PublishPipelineArtifact@1
            inputs:
              path: '$(Pipeline.Workspace)'
              ArtifactName: drop
              artifactType: 'pipeline'
          - task: CmdLine@2
            inputs:
              script: 'echo $(Pipeline.Workspace)'
  - stage: CD
    displayName: Deploy to App service
    dependsOn: CI
    condition: succeeded('CI')
    jobs:
      - job: DeployApp
        displayName: 'Deploy App'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzurePortalServiceConncetion'
              appType: 'webApp'
              WebAppName: 'davidcsizy'
              packageForLinux: '$(Pipeline.Workspace)/s/build'
