trigger:
  - master
stages:
  - stage: CICD
    displayName: Build publish deploy
    jobs:
      - job: CICD
        pool:
          vmImage: windows-latest
        steps:
          - task: AzureKeyVault@2
            inputs:
              connectedServiceName: 'AzurePortalServiceConncetion'
              keyVaultName: 'kv-resume-app'
              secretsFilter: '*'
              runAsPreJob: true
          - task: Bash@3
            displayName: Environment Variables
            env:
              REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
              REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
              REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKey)
            inputs:
              targetType: 'inline'
              script: 'env | sort'
          - task: Npm@1
            displayName: 'npm install'
            inputs:
              verbose: false

          - task: Npm@1
            displayName: 'npm run build'
            env:
              REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
              REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
              REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKey)
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'

          - task: PublishPipelineArtifact@1
            inputs:
              path: '$(Pipeline.Workspace)'
              ArtifactName: drop
              artifactType: 'pipeline'

  - stage: CD
    displayName: Deploy to App service
    dependsOn: CI
    condition: succeeded('CI')
    jobs:
      - job: DeployApp
        displayName: 'CD'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: AzureKeyVault@2
            inputs:
              connectedServiceName: 'AzurePortalServiceConncetion'
              keyVaultName: 'kv-resume-app'
              secretsFilter: '*'
              runAsPreJob: true
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(System.DefaultWorkingDirectory)'
          #- powershell: Get-ChildItem -Path '$(System.DefaultWorkingDirectory)/s' -recurse
          #- task: Bash@3
          #displayName: Environment Variables
          #env:
          #REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
          #REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
          #REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKey)
          - task: AzureRmWebAppDeployment@4
            #env:
            #REACT_APP_SEND_MESSAGE_SERVICE_ID: $(reactAppSendMessageServiceId)
            #REACT_APP_SEND_MESSAGE_TEMPLATE_ID: $(reactAppSendMessageTemplateId)
            #REACT_APP_SEND_MESSAGE_PUBLIC_KEY: $(reactAppSendMessagePublicKey)
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'AzurePortalServiceConncetion'
              appType: 'webApp'
              WebAppName: 'davidcsizy'
              packageForLinux: '$(System.DefaultWorkingDirectory)/s/build'
