stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            submodules: true
          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/src'
              output_location: './'
              azure_static_web_apps_api_token: '5f1fae9b684ef42d495791f004ae9831c077a207f6724f559144e0d61ca2facc1-369a9c80-e8d5-4ef9-99a1-2d013ea1bb62003129882'
