stages:
  - stage: CI
    jobs:
      - job: CI
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            submodules: true
          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/'
              output_location: '/'
              azure_static_web_apps_api_token: 'e0e11293d9fed12b05b488d0020a096a63006f35dfb194f4260dff135cf606f32-27936dac-81ff-4adb-b6fb-b1b4d4ebb967003130298'
